Add check for branch compatibility
This adds an extra stage to our test suite workflow to check that only
develop can be merged into main via PR.

diff --git a/.github/workflows/01-test-suite.yml b/.github/workflows/01-test-suite.yml
--- a/.github/workflows/01-test-suite.yml
+++ b/.github/workflows/01-test-suite.yml
@@ -5,6 +5,15 @@ on:
       - "**"
   pull_request:
 jobs:
+  check-branch:
+    name: Quit if PR target is invalid
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main' && github.head_ref != 'refs/heads/develop'
+    steps:
+      - name: Fail
+        run: |
+          echo "::error::Invalid PR: Only develop can be merged into main"
+          exit 1
   test:
     name: Run full test suite
     runs-on: ubuntu-latest
